apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-service
  template:
    metadata:
      labels:
        app: project-service
    spec:
      containers:
        - name: project-service
          image: project-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: NODE_ENV
              value: "development"
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "campus.user"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_NAME
              value: "campus_link_db"
